### ISSUE TITLE
The Story of the Five Monkeys

### ISSUE THREAD

**Issue by aghamidi** [aghamidi/Project#26]
https://www.youtube.com/watch?v=W2Jm1gzwocA

What is the topic of the lecture (series)? (3-5 sentences. Don't copy the title.)
Why is this topic important according to the lecturer (3-5 sentences)?

**Comment by IbnAbdullan-AlAthari** [comment]
Lecture by Shaykh Abu Adnan

Topic: The lecture starts off with a study conducted about how these five monkeys were shown bananas hung above them and when they wanted to go up to reach them water would be splashed on them, then whenever they would bring new monkeys the monkeys would prevent them from going up. A time came where they only had new monkeys and the monkeys wouldn't allow each other to go up and grab the monkeys not because they new what would happen because the previous monkeys told them not to do so. Than the Shaykh says how scientist claim that the closest animal in terms of intelligence to a human is a monkey. He relates how humans would not in the past and still do not follow the truth (Tawheed, Quran and Sunnah) because their forefathers never did that.

Why is it important: This topic is important because it explains very dangerous issues like blindly following, partisan-ism and arrogance that prevents non-Muslims from accepting Islam and Muslims from following the Quran and Sunnah properly.
